### ISSUE TITLE
Failed to minify

### ISSUE THREAD

**Issue by justinkiang** [doowb/ansi-colors#36] opened 2019-08-12 23:46 UTC
Trying to build a react proeject that uses this module and ran into the following issue

`Creating an optimized production build...
Failed to compile.

Failed to minify the code from this file: 

        ./node_modules/ansi-colors/index.js:3 
`

**Comment by doowb** [comment] 2019-08-13 00:58
@justinkiang can you provide more information?

What version of `ansi-colors` are you using?
Why did it fail to minify the code? Is there an actual error message?

You might have to do more than minifying the code.

**Comment by ThomLaGreca** [comment] 2019-08-28 23:52
@doowb I've gotten the exact same error. Struggling to find an actual error message. 

Failed to minify the code from this file: 
 	./node_modules/ansi-colors/index.js:3 

@justinkiang Did you find a fix for this?

**Comment by doowb** [comment] 2019-08-29 00:02
@ThomLaGreca can you provide more information?

Steps to reproduce?
Tools that you are using to minify? Babel? TypeScript? Flow? Webpack? Rollup? etc...

A minimum project that shows how the error occurs would be the best example.

Thanks.

**Comment by doowb** [comment] 2019-08-31 13:07
I ran into an issue similar to this on a project using `create-react-app`. The error message has a link to [this troubleshooting guide](https://create-react-app.dev/docs/troubleshooting#npm-run-build-fails-to-minify) that mentions it's due to an older version of `react-scripts`. If either of you are using something that uses `react-scripts`, this may be the issue you're running into.

I'm going to close this since the error is not in `ansi-colors`, but in how a bundler is trying to handle the JavaScript in `ansi-colors`.

**Closed by doowb** 2019-08-31 13:07 UTC
